# Generated by Django 4.2.7 on 2023-11-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0004_remove_song_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='preview_url',
            field=models.TextField(null=True),
        ),
    ]
